"""Auto-generated TypedMock stubs for IDE auto-completion.

Generated by typed-pytest-generator.
DO NOT EDIT MANUALLY.
"""

from __future__ import annotations

from .UserService import UserService_TypedMock, UserServiceMock

__all__ = [
    UserService_TypedMock,\n    UserServiceMock,
]
