"""Auto-generated TypedMock stubs for IDE auto-completion.

Generated by typed-pytest-generator.
DO NOT EDIT MANUALLY.
"""

from __future__ import annotations

from .UserService import UserService, UserService_TypedMock, UserServiceMock
from .ProductRepository import ProductRepository, ProductRepository_TypedMock, ProductRepositoryMock

__all__ = [
    UserService,\n    UserService_TypedMock,\n    UserServiceMock,\n    ProductRepository,\n    ProductRepository_TypedMock,\n    ProductRepositoryMock,
]
