"""Auto-generated stub file for ProductRepository.

Generated by typed-pytest-generator.
DO NOT EDIT MANUALLY.
"""

from __future__ import annotations

from typing import Any

import tests.fixtures.sample_classes as _orig_module


class ProductRepository:
    """Original class stub for type checking."""

    def find_all(self, limit: int) -> list: ...
    def find_by_id(self, product_id: str) -> tests.fixtures.sample_classes.Product | None: ...
    def search(self, query: str, max_results: int) -> list: ...

# Alias for TypedMock subclass (convenience)
from typed_pytest import TypedMock

class ProductRepository_TypedMock(TypedMock["tests.fixtures.sample_classes.ProductRepository"]):
    """TypedMock stub with ProductRepository method signatures."""

    def find_all(self, limit: int) -> MockedMethod[[int], list]: ...
    def find_by_id(self, product_id: str) -> MockedMethod[[str], tests.fixtures.sample_classes.Product | None]: ...
    def search(self, query: str, max_results: int) -> MockedMethod[[str, int], list]: ...

# Convenience alias
ProductRepositoryMock = ProductRepository_TypedMock
