"""Auto-generated stub file for UserService TypedMock.

Generated by typed-pytest-generator.
DO NOT EDIT MANUALLY.
"""

from __future__ import annotations

from typing import Any, Generic, TypeVar

from typed_pytest import (
    TypedMock,
    MockedMethod,
    AsyncMockedMethod,
    MockedProperty,
    MockedClassMethod,
    MockedStaticMethod,
)

import tests.fixtures.sample_classes as _orig_module


T = TypeVar("T")

class UserService_TypedMock(TypedMock["tests.fixtures.sample_classes.UserService"]):
    """TypedMock stub with UserService method signatures."""

    async def async_create_user(self, name: str, email: str) -> AsyncMockedMethod[[str, str], dict]: ...
    async def async_get_user(self, user_id: int) -> AsyncMockedMethod[[int], dict]: ...
    @property
    def connection_status(self) -> MockedProperty[str]: ...
    def create_user(self, name: str, email: str) -> MockedMethod[[str, str], dict]: ...
    def delete_user(self, user_id: int) -> MockedMethod[[int], bool]: ...
    @classmethod
    def from_config(config: dict) -> MockedClassMethod[[dict], UserService]: ...
    def get_user(self, user_id: int) -> MockedMethod[[int], dict]: ...
    @property
    def is_connected(self) -> MockedProperty[bool]: ...
    def update_user(self, user_id: int, name: str | None, email: str | None) -> MockedMethod[[int, str | None, str | None], dict]: ...
    @staticmethod
    def validate_email() -> MockedStaticMethod[[], bool]: ...

# Convenience alias
UserServiceMock = UserService_TypedMock
