"""Template generation for typed-pytest-generator stubs."""

from __future__ import annotations

from typing import Any

from typed_pytest_generator._inspector import MethodInfo, format_signature_params

# Template for generated .pyi file for each class
CLASS_STUB_TEMPLATE = '''\
"""Auto-generated stub file for {class_name} TypedMock.

Generated by typed-pytest-generator.
DO NOT EDIT MANUALLY.
"""

from __future__ import annotations

from typing import Any, Generic, TypeVar

from typed_pytest import (
    TypedMock,
    MockedMethod,
    AsyncMockedMethod,
    MockedProperty,
    MockedClassMethod,
    MockedStaticMethod,
)

{imports}

T = TypeVar("T")

class {class_name}_TypedMock(TypedMock["{full_name}"]):
    """TypedMock stub with {class_name} method signatures."""

{methods}

# Convenience alias
{class_name}Mock = {class_name}_TypedMock
'''

# Template for imports section
IMPORTS_TEMPLATE = '''\
import {module_name} as _orig_module
'''

# Template for method stubs
METHOD_TEMPLATE = '''\
    def {name}(self, {params}) -> MockedMethod[[{param_types}], {return_type}]: ...'''

ASYNC_METHOD_TEMPLATE = '''\
    async def {name}(self, {params}) -> AsyncMockedMethod[[{param_types}], {return_type}]: ...'''

PROPERTY_TEMPLATE = '''\
    @property
    def {name}(self) -> MockedProperty[{return_type}]: ...'''

CLASSMETHOD_TEMPLATE = '''\
    @classmethod
    def {name}({params}) -> MockedClassMethod[[{param_types}], {return_type}]: ...'''

STATICMETHOD_TEMPLATE = '''\
    @staticmethod
    def {name}({params}) -> MockedStaticMethod[[{param_types}], {return_type}]: ...'''


def _format_type(typ: Any) -> str:
    """Format a type annotation as a string."""
    if typ is None or typ == "Any" or typ is Any:
        return "Any"

    if hasattr(typ, "__name__"):
        return typ.__name__

    if hasattr(typ, "__origin__"):
        origin = typ.__origin__
        if hasattr(origin, "__name__"):
            args = ", ".join(_format_type(arg) for arg in typ.__args__)
            return f"{origin.__name__}[{args}]"

    return str(typ)


def _format_param_types(params: list) -> str:
    """Format parameters as type list for MockedMethod."""
    return ", ".join(_format_type(p.annotation) for p in params if p.annotation != "Any")


def _format_params(params: list) -> str:
    """Format parameters for method signature."""
    if not params:
        return ""

    param_strs = []
    for param in params:
        ann = _format_type(param.annotation)
        param_strs.append(f"{param.name}: {ann}")
    return ", ".join(param_strs)


def generate_class_stub(
    class_name: str,
    full_name: str,
    methods: list[MethodInfo],
) -> str:
    """Generate a .pyi stub for a single class.

    Args:
        class_name: Name of the class (e.g., "UserService")
        full_name: Fully qualified name (e.g., "mypkg.services.UserService")
        methods: List of MethodInfo objects

    Returns:
        Generated .pyi file content
    """
    # Extract module path for import
    module_name = full_name.rsplit(".", 1)[0] if "." in full_name else full_name

    # Generate method stubs
    method_lines: list[str] = []

    for method in methods:
        params = method.parameters
        params_str = _format_params(params)
        param_types = _format_param_types(params)
        return_type = _format_type(method.return_annotation)

        if method.method_type == "async":
            line = ASYNC_METHOD_TEMPLATE.format(
                name=method.name,
                params=params_str,
                param_types=param_types,
                return_type=return_type,
            )
        elif method.method_type == "property":
            line = PROPERTY_TEMPLATE.format(
                name=method.name,
                return_type=return_type,
            )
        elif method.method_type == "classmethod":
            line = CLASSMETHOD_TEMPLATE.format(
                name=method.name,
                params=params_str,
                param_types=param_types,
                return_type=return_type,
            )
        elif method.method_type == "staticmethod":
            line = STATICMETHOD_TEMPLATE.format(
                name=method.name,
                params=params_str,
                param_types=param_types,
                return_type=return_type,
            )
        else:  # regular method
            line = METHOD_TEMPLATE.format(
                name=method.name,
                params=params_str,
                param_types=param_types,
                return_type=return_type,
            )

        method_lines.append(line)

    # Generate import section
    imports = IMPORTS_TEMPLATE.format(module_name=module_name)

    # Generate the full stub
    return CLASS_STUB_TEMPLATE.format(
        class_name=class_name,
        full_name=full_name,
        imports=imports,
        methods="\n".join(method_lines),
    )


def generate_init_stub(class_names: list[str]) -> str:
    """Generate __init__.pyi with exports.

    Args:
        class_names: List of class names that have stubs

    Returns:
        Generated __init__.pyi content
    """
    # Generate import statements
    imports = []
    exports = []

    for name in class_names:
        imports.append(f"from .{name} import {name}_TypedMock, {name}Mock")
        exports.append(f"    {name}_TypedMock")
        exports.append(f"    {name}Mock")

    return f'''\
"""Auto-generated TypedMock stubs for IDE auto-completion.

Generated by typed-pytest-generator.
DO NOT EDIT MANUALLY.
"""

from __future__ import annotations

{chr(10).join(imports)}

__all__ = [
{",\\n".join(exports)},
]
'''
