"""Type stubs for typed-pytest - provides IDE auto-completion."""

from __future__ import annotations

from typing import Any, Generic, TypeVar

_T = TypeVar("_T")

class TypedMock(Generic[_T]):
    """Type-safe mock that preserves original type hints."""

    _mock: Any

    def __init__(
        self,
        spec: type[_T] | None = None,
        *,
        wraps: _T | None = None,
        name: str | None = None,
        spec_set: type[_T] | None = None,
        **kwargs: Any,
    ) -> None: ...
    def __class_getitem__(cls, item: type[_T]) -> type[TypedMock[_T]]: ...
    def __getattr__(self, name: str) -> MockedMethod: ...  # Auto-completion
    def __repr__(self) -> str: ...
    @property
    def typed_class(self) -> type[_T] | None: ...
    @property
    def call_count(self) -> int: ...
    @property
    def called(self) -> bool: ...
    @property
    def return_value(self) -> Any: ...
    @return_value.setter
    def return_value(self, value: Any) -> None: ...
    @property
    def side_effect(self) -> Any: ...
    @side_effect.setter
    def side_effect(self, value: Any) -> None: ...
    def assert_called(self) -> None: ...
    def assert_called_once(self) -> None: ...
    def assert_called_with(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_called_once_with(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_any_call(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_not_called(self) -> None: ...
    def assert_has_calls(self, calls: list[Any], any_order: bool = False) -> None: ...
    def reset_mock(self) -> None: ...
    @property
    def call_args(self) -> Any: ...
    @property
    def call_args_list(self) -> list[Any]: ...

def typed_mock(
    cls: type[_T],
    /,
    *,
    spec_set: bool = False,
    name: str | None = None,
    **kwargs: Any,
) -> TypedMock[_T]: ...

class TypedMocker:
    """Type-safe mocker wrapping pytest-mock's MockerFixture."""

    def __init__(self, mocker: Any) -> None: ...
    def mock(self, cls: type[_T], /, **kwargs: Any) -> TypedMock[_T]: ...
    def patch(
        self,
        target: str,
        new: type[_T] | None = None,
        **kwargs: Any,
    ) -> Any: ...
    def patch_object(
        self,
        target: object,
        attribute: str,
        new: type[_T] | None = None,
        **kwargs: Any,
    ) -> Any: ...
    def patch_dict(self, in_dict: dict[str, Any], /, **kwargs: Any) -> Any: ...
    def spy(self, obj: object, name: str) -> Any: ...

class MockedMethod:
    """Mocked method wrapper for auto-completion."""

    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def assert_called(self) -> None: ...
    def assert_called_once(self) -> None: ...
    def assert_called_with(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_called_once_with(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_any_call(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_not_called(self) -> None: ...
    def assert_has_calls(self, calls: list[Any], any_order: bool = False) -> None: ...

    # Async assertion methods for async mock compatibility
    def assert_awaited(self) -> None: ...
    def assert_awaited_once(self) -> None: ...
    def assert_awaited_with(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_awaited_once_with(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_has_awaits(self, calls: list[Any], any_order: bool = False) -> None: ...
    @property
    def return_value(self) -> Any: ...
    @return_value.setter
    def return_value(self, value: Any) -> None: ...
    @property
    def side_effect(self) -> Any: ...
    @side_effect.setter
    def side_effect(self, value: Any) -> None: ...
    @property
    def call_count(self) -> int: ...
    @property
    def called(self) -> bool: ...
    @property
    def call_args(self) -> Any: ...
    @property
    def call_args_list(self) -> list[Any]: ...

    # Async mock compatibility properties
    @property
    def await_count(self) -> int: ...
    @property
    def await_args(self) -> Any: ...
    @property
    def await_args_list(self) -> list[Any]: ...
    def reset_mock(self) -> None: ...

class AsyncMockedMethod:
    """Mocked async method wrapper."""

    async def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def assert_called(self) -> None: ...
    def assert_called_once(self) -> None: ...
    def assert_called_with(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_called_once_with(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_any_call(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_not_called(self) -> None: ...
    def assert_awaited(self) -> None: ...
    def assert_awaited_once(self) -> None: ...
    def assert_awaited_with(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_awaited_once_with(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_has_awaits(self, calls: list[Any], any_order: bool = False) -> None: ...
    @property
    def return_value(self) -> Any: ...
    @return_value.setter
    def return_value(self, value: Any) -> None: ...
    @property
    def side_effect(self) -> Any: ...
    @side_effect.setter
    def side_effect(self, value: Any) -> None: ...
    @property
    def call_count(self) -> int: ...
    @property
    def called(self) -> bool: ...
    @property
    def call_args(self) -> Any: ...
    @property
    def call_args_list(self) -> list[Any]: ...
    @property
    def await_count(self) -> int: ...
    @property
    def await_args(self) -> Any: ...
    @property
    def await_args_list(self) -> list[Any]: ...
    def reset_mock(self) -> None: ...

class MockProtocol:
    """Protocol for runtime mock compatibility checks."""

    def assert_called(self) -> None: ...
    def assert_called_once(self) -> None: ...
    def assert_called_with(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_called_once_with(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_any_call(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_not_called(self) -> None: ...
    @property
    def return_value(self) -> Any: ...
    @property
    def side_effect(self) -> Any | None: ...
    @property
    def call_count(self) -> int: ...
    @property
    def call_args(self) -> Any: ...
    @property
    def call_args_list(self) -> list[Any]: ...
    @property
    def called(self) -> bool: ...
    def reset_mock(self) -> None: ...

class AsyncMockProtocol(MockProtocol):
    """Protocol for async mock compatibility checks."""

    def assert_awaited(self) -> None: ...
    def assert_awaited_once(self) -> None: ...
    def assert_awaited_with(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_awaited_once_with(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def await_count(self) -> int: ...
    @property
    def await_args(self) -> Any: ...
    @property
    def await_args_list(self) -> list[Any]: ...

__version__: str
